# A super simple Compose setup.
# This assumes you already have a reverse proxy pointing at
# localhost:8000 which handles SSL termination for HTTPS.
#
# To run this: set the NEXT_PUBLIC_WEB_ADDRESS and NEXT_PUBLIC_API_ADDRESS
# environment variables to the public URL of your server. Remember that these
# are full URLs, scheme included, so ensure `https://` is included.
#
services:
  storyden:
    image: ghcr.io/southclaws/storyden:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data:/storyden/data
    environment:
      - NEXT_PUBLIC_WEB_ADDRESS=${NEXT_PUBLIC_WEB_ADDRESS}
      - NEXT_PUBLIC_API_ADDRESS=${NEXT_PUBLIC_API_ADDRESS}
